### ISSUE TITLE
Request: Per site settings

### ISSUE THREAD

**Issue by sclient** [ValentinG0/firelux2#3]
Have a few sites that I have used a style to set black/used night mode on/are already black, and this makes them look really bad (and is somewhat pointless).

Would like to have at least like 10 or so that I could set this to off for.

**Comment by ValentinG0** [comment]
A blacklist will be available in the next version in order to disable the extension for some sites.

**Comment by ValentinG0** [comment]
Ignore list have been added in version [v2.0.1.0](https://framagit.org/ValentinG/firelux2/-/tags/v2.0.1.0) (dcb29b441bdf020f46ef3ed574bb82e71da09503).
